### ISSUE TITLE
Rerun compilation if env changed

### ISSUE THREAD

**Issue by segeljakt** [EkardNT/const_env#5]
Hi, thank you for this cool crate. It works well but I have one problem. Cargo seems to cache compilation and not recompile when the environment variables change. Is it possible to add some similar functionality to:
```rust
// build.rs
println!("cargo:rerun-if-env-changed=FOO");
```

**Comment by EkardNT** [comment]
I've published a new `0.1.3` version to crates.io which has a `tracked` feature you can use to achieve this. This will be a nightly-only feature until https://github.com/rust-lang/rust/issues/74690 is merged.
